"""Firestore collection names — SSOT: docs/05 §1 (do not rename)."""

PRODUCTS = "products"
LISTINGS = "listings"
PRICE_HISTORY = "price_history"
GPU_VENDORS = "gpu_vendors"
GPU_FAMILIES = "gpu_families"
GPU_MODELS = "gpu_models"
BOARD_PARTNERS = "board_partners"
MALLS = "malls"
SELLERS = "sellers"
CRAWL_JOBS = "crawl_jobs"
CRAWL_LOGS = "crawl_logs"
VALIDATION_LOGS = "validation_logs"
